import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import RAPIER from '@dimforge/rapier3d-compat';
import {terrainSampler,seatOnGround,alignToGround} from '../src/grounding.js';
import {buildTerrain} from '../src/terrain.js';
import {makeMaterials} from '../src/models.js';
await RAPIER.init();
function gap(geometry,matrix,height){const v=new THREE.Vector3(),vertices=geometry.attributes.position;let min=Infinity;for(let i=0;i<vertices.count;i++){v.fromBufferAttribute(vertices,i).applyMatrix4(matrix);min=Math.min(min,v.y-height(v.x,v.z));}return min;}
test('height sampler matches triangle surface rather than a smooth height approximation',()=>{const geo=new THREE.PlaneGeometry(20,20,4,4);geo.rotateX(-Math.PI/2);const p=geo.attributes.position;for(let i=0;i<p.count;i++)p.setY(i,Math.sin(p.getX(i))*.8+Math.cos(p.getZ(i))*.9);const height=terrainSampler(geo,20,4),mesh=new THREE.Mesh(geo,new THREE.MeshBasicMaterial()),ray=new THREE.Raycaster();mesh.updateMatrixWorld();for(const [x,z] of [[-8,-7],[-1,2],[3.1,3.8],[9,-5.2]]){ray.set(new THREE.Vector3(x,30,z),new THREE.Vector3(0,-1,0));const hit=ray.intersectObject(mesh)[0];assert.ok(Math.abs(hit.point.y-height(x,z))<1e-6);}});
test('scaled and rotated objects contact sloped terrain at their actual geometry',()=>{const height=(x,z)=>x*.3-z*.15,obj=new THREE.Object3D(),geo=new THREE.CylinderGeometry(.45,.45,1.3,12);obj.position.set(5,80,-3);obj.scale.set(1,1.2,1);obj.rotation.y=.7;alignToGround(obj,height);seatOnGround(obj,geo,height,.005);assert.ok(Math.abs(gap(geo,obj.matrix,height)+.005)<1e-6);});
test('all spawned rocks, drums and plant instances are seated on the terrain mesh',()=>{const world=new RAPIER.World({x:0,y:-18,z:0}),textures=Object.fromEntries(['sand','normal','height','armor','concrete','rock'].map(k=>[k,new THREE.Texture()])),props=[],env=buildTerrain(new THREE.Group(),world,textures,makeMaterials(textures),props,new Map());for(const prop of props){if(!['rock','barrel'].includes(prop.kind))continue;prop.mesh.updateMatrix();assert.ok(gap(prop.mesh.geometry,prop.mesh.matrix,env.surfaceHeight)<=.001,`${prop.kind} floats`);assert.ok(prop.mesh.quaternion.angleTo(new THREE.Quaternion().copy(prop.body.rotation()))<.001);if(prop.kind==='barrel')assert.equal(prop.collider.shapeType(),RAPIER.ShapeType.Cylinder);}const matrix=new THREE.Matrix4();for(const plants of [env.shrubs,env.branches])for(let i=0;i<plants.count;i++){plants.getMatrixAt(i,matrix);assert.ok(gap(plants.geometry,matrix,env.surfaceHeight)<.001,`plant ${i} floats`);}world.free();});
