import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {createTank,makeMaterials} from '../src/models.js';
import {TANKS} from '../src/config.js';
const materials=()=>makeMaterials({sand:null,normal:null,height:null,armor:null,concrete:null,rock:null});
test('Kestrel detail variants share articulation and muzzle while cutting gameplay polygons',()=>{const high=createTank('scout',materials(),false,'high'),low=createTank('scout',materials(),false,'low');assert.ok(low.root.userData.triangles<high.root.userData.triangles*.3,`${low.root.userData.triangles} vs ${high.root.userData.triangles}`);for(const model of [high,low]){assert.equal(model.root.name,'Kestrel');assert.equal(model.root.scale.x,TANKS.scout.scale);assert.equal(model.wheels.length,16);model.turret.rotation.y=.7;model.gun.rotation.x=-.2;model.root.updateMatrixWorld(true);}assert.ok(high.muzzlePoint.getWorldPosition(new THREE.Vector3()).distanceTo(low.muzzlePoint.getWorldPosition(new THREE.Vector3()))<1e-6);assert.ok(high.muzzlePoint.getWorldDirection(new THREE.Vector3()).distanceTo(low.muzzlePoint.getWorldDirection(new THREE.Vector3()))<1e-6);});
test('Kestrel geometry is finite, outward-facing and sits on its tracks',()=>{for(const detail of ['high','low']){const model=createTank('scout',materials(),false,detail);model.root.updateMatrixWorld(true);const hits=new THREE.Raycaster(new THREE.Vector3(0,10,-1.2),new THREE.Vector3(0,-1,0)).intersectObject(model.root,true);assert.ok(hits.length&&hits[0].face.normal.y>.3);const bounds=new THREE.Box3().setFromObject(model.root);assert.ok(Math.abs(bounds.min.y/TANKS.scout.scale+.98)<.02,`track base ${bounds.min.y}`);model.root.traverse(mesh=>{if(!mesh.isMesh)return;const p=mesh.geometry.attributes.position;assert.ok([...p.array].every(Number.isFinite));if(mesh.material===model.armor)assert.ok([...mesh.geometry.attributes.uv.array].every(Number.isFinite));});}});
test('Kestrel wreck darkening reaches the camouflaged armor material',()=>{const model=createTank('scout',materials(),false,'high');let armored=0;model.root.traverse(o=>{if(o.isMesh&&o.material===model.armor)armored++;});assert.ok(armored>=3);});
