import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import RAPIER from '@dimforge/rapier3d-compat';
import {Game} from '../src/game.js';
import {Navigation} from '../src/navigation.js';
import {makeMaterials} from '../src/models.js';
await RAPIER.init();
function setup(){const g=Object.create(Game.prototype);Object.assign(g,{time:0,world:new RAPIER.World({x:0,y:-18,z:0}),root:new THREE.Group(),materials:makeMaterials({sand:null,normal:null,height:null,armor:null,concrete:null,rock:null}),tanks:[],entities:new Map(),props:[],nextId:1,rand:()=>.5,fx:{dust(){},tread(){}},ammo:'ap'});g.world.createCollider(RAPIER.ColliderDesc.cuboid(150,.2,150).setTranslation(0,-.2,0));const t=g.spawnTank('jeep',0,-15,true);t.body.setTranslation({x:0,y:1,z:-15},true);g.world.step();g.navigation=new Navigation(g);g.wall=(x,z,w,d)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,5,d));const body=g.world.createRigidBody(RAPIER.RigidBodyDesc.fixed().setTranslation(x,2.5,z));const collider=g.world.createCollider(RAPIER.ColliderDesc.cuboid(w/2,2.5,d/2),body);const prop={mesh,body,collider};g.props.push(prop);g.entities.set(collider.handle,prop);g.world.step();return prop;};return {g,t};}
test('jeep physically navigates around a wall without clipping or teleporting',()=>{const {g,t}=setup();g.wall(0,0,14,2);const target=new THREE.Vector3(0,1,17);let maxSide=0,arrived=false;for(let i=0;i<2400;i++){g.time+=1/60;const cmd=g.navigation.steer(t,target,1/60,.8);g.drive(t,{...cmd,aim:target,fire:false,secondary:false},1/60);g.world.step();const p=t.body.translation();maxSide=Math.max(maxSide,Math.abs(p.x));if(Math.hypot(p.x,p.z-17)<5){arrived=true;break;}}assert.ok(maxSide>9,`must clear wall width: ${maxSide}`);assert.ok(arrived,`failed to arrive: ${JSON.stringify(t.body.translation())}`);g.world.free();});
test('routes avoid corner cutting and refresh after cover is destroyed',()=>{const {g,t}=setup();const wall=g.wall(0,0,14,2);const start=new THREE.Vector3().copy(t.body.translation()),goal=new THREE.Vector3(0,1,17),nav=g.navigation;const route=nav.route(start,goal);assert.ok(route.length);assert.ok(route.some(p=>Math.abs(p.x)>9));for(let i=1;i<route.length;i++)assert.ok(nav.clearGrid(route[i-1],route[i]),'route clips a corner');wall.destroyed=true;g.time=2;const cleared=nav.route(start,goal);const length=path=>path.slice(1).reduce((sum,p,i)=>sum+p.distanceTo(path[i]),0);assert.ok(length(cleared)<length(route));assert.ok(cleared.every(p=>Math.abs(p.x)<2));g.world.free();});
test('lack of movement triggers a finite reverse/turn recovery even with spinning wheels',()=>{const {g,t}=setup();t.speed=8;let reversed=false;for(let i=0;i<150;i++){g.time+=1/60;const cmd=g.navigation.steer(t,new THREE.Vector3(0,1,40),1/60,.8);if(cmd.throttle<0)reversed=true;}assert.ok(reversed);assert.ok(t.navigation.recovery>0&&t.navigation.recovery<2.3);g.world.free();});

test('jeep escapes a concave ruin through its opening instead of pushing into the back wall',()=>{const {g,t}=setup();g.wall(-8,0,2,20);g.wall(8,0,2,20);g.wall(0,9,16,2);t.body.setTranslation({x:0,y:1,z:0},true);g.world.step();const target=new THREE.Vector3(0,1,24);let exitedOpening=false,arrived=false;for(let i=0;i<3600;i++){g.time+=1/60;const cmd=g.navigation.steer(t,target,1/60,.8);g.drive(t,{...cmd,aim:target,fire:false,secondary:false},1/60);g.world.step();const p=t.body.translation();if(p.z<-12)exitedOpening=true;if(Math.hypot(p.x,p.z-24)<5){arrived=true;break;}}assert.ok(exitedOpening,'must route out through the opening');assert.ok(arrived,JSON.stringify(t.body.translation()));g.world.free();});
