import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import RAPIER from '@dimforge/rapier3d-compat';
import {Game} from '../src/game.js';
import {TANKS,AMMO,FIXED_DT,GRAVITY,ballisticElevation,approachAngle,angleDelta,terrainHeight} from '../src/config.js';
import {resolveDirectionalAim} from '../src/aiming.js';
import {createDebris} from '../src/debris.js';
import {Effects} from '../src/effects.js';
import {Ragdolls} from '../src/ragdolls.js';
import {makeMaterials} from '../src/models.js';
await RAPIER.init();
function harness(type='medium'){
 const g=Object.create(Game.prototype);Object.assign(g,{world:new RAPIER.World({x:0,y:GRAVITY,z:0}),root:new THREE.Group(),materials:makeMaterials({sand:null,normal:null,height:null,armor:null,concrete:null,rock:null}),tanks:[],entities:new Map(),nextId:1,rand:()=>.5,fx:{tread(){},dust(){}},ammo:'ap'});g.world.timestep=FIXED_DT;g.world.createCollider(RAPIER.ColliderDesc.cuboid(200,.2,200).setTranslation(0,-.2,0));g.player=g.spawnTank(type,0,0,false);g.world.step();return g;
}
function tick(g,frames,cmd={}){for(let i=0;i<frames;i++){g.drive(g.player,{throttle:0,steer:0,brake:false,aim:new THREE.Vector3(0,0,50),fire:false,secondary:false,...cmd},FIXED_DT);g.world.step();}}
for(const type of Object.keys(TANKS))test(`${type} turbo accelerates harder, exhausts and recharges`,()=>{
 const normal=harness(type),boost=harness(type);
 try{
  tick(normal,120);tick(boost,120);tick(normal,180,{throttle:1});tick(boost,180,{throttle:1,boost:true});
  assert.ok(boost.player.speed>normal.player.speed*1.3,`${boost.player.speed} vs ${normal.player.speed}`);
  assert.ok(boost.player.turboCharge<.2);tick(boost,90,{throttle:1,boost:true});assert.equal(boost.player.turboLocked,true);assert.equal(boost.player.boosting,false);
  tick(boost,660);assert.equal(boost.player.turboCharge,1);assert.equal(boost.player.turboLocked,false);
  tick(boost,1,{throttle:1,boost:true});assert.equal(boost.player.boosting,true);
 }finally{normal.world.free();boost.world.free();}
});
test('turret takes shortest path across +/- PI and obeys traverse rate',()=>{const a=3.12,b=-3.1;const next=approachAngle(a,b,.02);assert.ok(Math.abs(angleDelta(a,next)-.02)<1e-9);assert.ok(Math.abs(approachAngle(0,.01,.2)-.01)<1e-12);});
test('ballistic elevation reaches target across ammunition velocities',()=>{for(const ammo of Object.values(AMMO))for(const d of [10,40,80]){const h=-1.7,a=ballisticElevation(d,h,ammo.speed),time=d/(ammo.speed*Math.cos(a));const y=ammo.speed*Math.sin(a)*time+.5*GRAVITY*time*time;assert.ok(Math.abs(y-h)<1e-7);}});
test('terrain remains finite and has elevated dunes',()=>{assert.ok(terrainHeight(23,8)>4);for(let x=-110;x<=110;x+=5)for(let z=-110;z<=110;z+=5)assert.ok(Number.isFinite(terrainHeight(x,z)));});
for(const type of Object.keys(TANKS))test(`${type} suspension settles, accelerates and brakes on rigid ground`,()=>{const g=harness(type);tick(g,240);const p=g.player;const settled=p.body.translation();assert.ok(settled.y>.7&&settled.y<1.6,JSON.stringify(settled));assert.ok(p.grounded>=4);tick(g,180,{throttle:1});assert.ok(p.speed>6,`speed=${p.speed}`);const moving=p.speed;tick(g,120,{brake:true});assert.ok(Math.abs(p.speed)<moving*.25,`brake=${p.speed}`);const q=p.body.rotation();assert.ok(Math.abs(q.x)<.25&&Math.abs(q.z)<.25);g.world.free();});
test('shell body follows gravity and CCD catches thin wall at APDS velocity',()=>{const w=new RAPIER.World({x:0,y:GRAVITY,z:0});w.timestep=FIXED_DT;const eq=new RAPIER.EventQueue(true);w.createCollider(RAPIER.ColliderDesc.cuboid(3,3,.05).setTranslation(0,2,5));const b=w.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(0,2,0).setLinvel(0,0,100).setCcdEnabled(true));w.createCollider(RAPIER.ColliderDesc.ball(.11).setActiveEvents(RAPIER.ActiveEvents.COLLISION_EVENTS),b);let collided=false;for(let i=0;i<10;i++){w.step(eq);eq.drainCollisionEvents((a,b,start)=>{if(start)collided=true;});}assert.ok(collided);assert.ok(b.translation().z<5.1);assert.ok(b.translation().y<2);eq.free();w.free();});
test('mesh collision allows a tank to crawl over a low sloped rock',()=>{const g=harness('medium');const geo=new THREE.DodecahedronGeometry(1,0);geo.scale(2,.5,2.5);geo.translate(0,.3,9);const vertices=new Float32Array(geo.attributes.position.array),indices=Uint32Array.from({length:vertices.length/3},(_,i)=>i);g.world.createCollider(RAPIER.ColliderDesc.trimesh(vertices,indices).setFriction(.85));tick(g,180);let highest=0;for(let i=0;i<360;i++){tick(g,1,{throttle:.65});highest=Math.max(highest,g.player.body.translation().y);}assert.ok(g.player.body.translation().z>15,`stuck at ${JSON.stringify(g.player.body.translation())}`);assert.ok(highest>1.35,`did not climb: ${highest}`);g.world.free();});
test('barrel solution converges to cursor even with a pitched and rolled hull',()=>{const g=harness();const t=g.player;t.body.setBodyType(RAPIER.RigidBodyType.Fixed,true);t.body.setTranslation({x:0,y:1.1,z:0},true);t.body.setRotation(new THREE.Quaternion().setFromEuler(new THREE.Euler(.19,1.2,.08,'YXZ')),true);g.world.step();const aim=new THREE.Vector3(23,0,35);tick(g,240,{aim});g.prediction=new THREE.Vector3();g.predict();const error=g.prediction.distanceTo(aim);assert.ok(error<1.3,`impact error ${error}: ${JSON.stringify(g.prediction)}`);g.world.free();});
test('a driven tank launches from a short dune and lands upright',()=>{const g=harness('scout');const terrain=new THREE.PlaneGeometry(80,100,100,130);terrain.rotateX(-Math.PI/2);const pos=terrain.attributes.position;for(let i=0;i<pos.count;i++){const z=pos.getZ(i);pos.setY(i,2.7*Math.exp(-((z-16)**2/20)));}g.world.createCollider(RAPIER.ColliderDesc.trimesh(new Float32Array(pos.array),new Uint32Array(terrain.index.array)));tick(g,150);let airborne=0,maxHeight=0;for(let i=0;i<360;i++){tick(g,1,{throttle:1});if(g.player.grounded===0&&g.player.body.translation().z>12)airborne++;maxHeight=Math.max(maxHeight,g.player.body.translation().y);}assert.ok(airborne>4,`no jump: ${airborne} airborne frames`);assert.ok(maxHeight>3.4,`height=${maxHeight}`);assert.ok(Math.abs(g.player.body.rotation().x)<.35,'landed upright');g.world.free();});

test('jeeps are weak, wheeled, and carry a separate driver and gunner',()=>{const g=harness();const jeep=g.spawnTank('jeep',10,0,true);assert.equal(jeep.hp,100);assert.equal(jeep.wheels.length,4);assert.equal(jeep.crew.length,2);assert.ok(jeep.crew.every(c=>c.parts.length===11));assert.ok(AMMO.ap.damage*TANKS.scout.damage>jeep.hp);assert.ok(jeep.cfg.reload<=.15);g.world.free();});
test('jeep machine-gun rounds are individual physical objects with minimal damage',()=>{const g=harness();g.shells=[];g.fx.muzzle=()=>{};g.audio={boom(){}};const jeep=g.spawnTank('jeep',0,10,true);g.fire(jeep,false);assert.equal(g.shells.length,1);const bullet=g.shells[0];assert.equal(bullet.secondary,true);assert.equal(bullet.damage,1.2);assert.equal(jeep.reload,.12);assert.ok(bullet.body.isDynamic());const before=g.player.hp;g.impact(bullet,g.player);assert.ok(Math.abs(g.player.hp-(before-1.2))<1e-7);g.world.free();});
test('ejected crew remain jointed, land, and leave one smear when driven over',()=>{const g=harness();const jeep=g.spawnTank('jeep',12,0,true);let smears=0;const manager=new Ragdolls(g.world,g.root,{smear(){smears++;}});const rag=manager.eject(jeep.crew[0],new THREE.Vector3(5,7,0));assert.equal(rag.parts.length,11);assert.equal(rag.joints.length,10);const initial=rag.parts[0].body.translation().y;let high=initial;for(let i=0;i<300;i++){g.world.step();manager.update(FIXED_DT,null);high=Math.max(high,rag.parts[0].body.translation().y);}assert.ok(high>initial+.4,'crew launches upward');const torso=rag.parts[0].body.translation();assert.ok(torso.y<.8,'crew lands');assert.ok(rag.parts.every(p=>Number.isFinite(p.body.translation().x)));g.player.body.setTranslation({x:torso.x,y:1,z:torso.z},true);g.player.body.setRotation({x:0,y:0,z:0,w:1},true);g.player.grounded=6;g.player.speed=4;manager.update(FIXED_DT,g.player);assert.equal(smears,1);assert.ok(manager.items.length>=6&&manager.items.length<=8);assert.ok(manager.items.every(r=>r.limb));manager.update(FIXED_DT,g.player);assert.equal(smears,1,'no duplicate smear');g.world.free();});
test('directional aiming auto-ranges the same enemy regardless of cursor distance',()=>{const g=harness();const enemy=g.spawnTank('jeep',0,30,true);g.world.step();const near=resolveDirectionalAim(g,new THREE.Vector3(0,0,5)),far=resolveDirectionalAim(g,new THREE.Vector3(0,90,90));assert.equal(near.target.entity,enemy);assert.equal(far.target.entity,enemy);assert.ok(near.point.distanceTo(far.point)<1e-9);assert.ok(near.point.y>0,'aim at chassis, not mouse ground elevation');enemy.dead=true;assert.equal(resolveDirectionalAim(g,new THREE.Vector3(0,0,30)).target,null);g.world.free();});
test('directional targeting ignores enemies behind physical cover and outside the bearing',()=>{const g=harness();g.spawnTank('jeep',0,30,true);g.spawnTank('jeep',20,0,true);g.world.createCollider(RAPIER.ColliderDesc.cuboid(3,4,.5).setTranslation(0,2,15));g.world.step();assert.equal(resolveDirectionalAim(g,new THREE.Vector3(0,0,8)).target,null);const clear=resolveDirectionalAim(g,new THREE.Vector3(8,0,0));assert.equal(clear.target.entity.type,'jeep');g.world.free();});
test('destruction emits shaped fragments rather than placeholder boxes',()=>{const g=harness();for(const kind of ['earth','masonry','metal','vehicle'])for(let i=0;i<6;i++){const f=createDebris(g.materials,kind,i,()=>.5);assert.ok(f.vertices.length>=12);f.mesh.traverse(o=>{if(o.isMesh)assert.notEqual(o.geometry.type,'BoxGeometry');});assert.ok(RAPIER.ColliderDesc.convexHull(f.vertices));}g.world.free();});
test('explosions and cannon shots emit generated fire, embers, dust and bounded fading lights',()=>{const fx=new Effects(new THREE.Scene(),new THREE.Texture());fx.cannon(new THREE.Vector3(0,2,0),new THREE.Vector3(0,0,1),new THREE.Vector3(),1);assert.ok(fx.muzzleFlashes.some(f=>f.life>0&&f.material.uniforms.cannon.value===1));assert.ok(fx.particles.some(p=>p.kind==='dust'));for(let i=0;i<12;i++)fx.explosion(new THREE.Vector3(),1);assert.equal(fx.lights.length,6);assert.ok(fx.lights.some(l=>l.light.intensity>0));assert.ok(fx.particles.some(p=>p.kind==='ember'));fx.update(1);assert.ok(fx.lights.every(l=>l.light.intensity===0));});
test('auto-ranging leads a moving jeep rather than snapping shots behind it',()=>{const g=harness();const enemy=g.spawnTank('jeep',0,40,true);enemy.body.setLinvel({x:5,y:0,z:0},true);g.world.step();const solution=resolveDirectionalAim(g,new THREE.Vector3(0,0,10));assert.equal(solution.target.entity,enemy);assert.ok(solution.point.x>enemy.body.translation().x+2,'lead forward along target velocity');g.world.free();});
test('tank ramming a jeep makes chassis contact and transfers momentum without treating it as ground',()=>{const g=harness();const jeep=g.spawnTank('jeep',0,9,true);jeep.body.setTranslation({x:0,y:1,z:9},true);const command={throttle:0,steer:0,brake:false,aim:new THREE.Vector3(0,0,50),fire:false,secondary:false};let contacts=0,maxRise=0;for(let i=0;i<210;i++){g.drive(g.player,{...command,throttle:i>60?1:0},FIXED_DT);g.drive(jeep,command,FIXED_DT);g.world.step();g.world.contactPair(g.player.collider,jeep.collider,()=>contacts++);maxRise=Math.max(maxRise,g.player.body.translation().y-jeep.body.translation().y);}assert.ok(contacts>0,'chassis must collide');assert.ok(jeep.body.translation().z>11,'tank should push the lighter jeep');assert.ok(g.player.body.translation().z<jeep.body.translation().z,'tank must not pass through jeep');assert.ok(maxRise<1.1,`suspension must not climb onto jeep: ${maxRise}`);g.world.free();});

test('tank climbs and clears a destroyed jeep from front and side',()=>{for(const yaw of [0,Math.PI/2]){const g=harness(),jeep=g.spawnTank('jeep',0,9,true);jeep.dead=true;g.prepareJeepWreck(jeep);jeep.body.setTranslation({x:0,y:.48,z:9},true);jeep.body.setRotation(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),yaw),true);jeep.body.setBodyType(RAPIER.RigidBodyType.Fixed,true);tick(g,180);let highest=0;for(let i=0;i<420;i++){tick(g,1,{throttle:.65});highest=Math.max(highest,g.player.body.translation().y);}assert.ok(g.player.body.translation().z>15,`stuck at ${JSON.stringify(g.player.body.translation())}`);assert.ok(highest>1.12,`did not climb wreck: ${highest}`);g.world.free();}});
