import {nextPaint,warmScene} from './loading.js';
import {prepareGarage,selectGarageTank,detachGarageCache} from './garage-cache.js';
import {ReconDrone} from './recon-drone.js';
import {updateVehicleDust} from './vehicle-dust.js';
import {PlayerAwareness} from './awareness.js';
import {snapshotVehicle,presentVehicle,followCamera} from './motion-presentation.js';
import {TURBO,updateTurbo} from './turbo.js';
import {PATROL_SITES} from './world-layout.js';
import {createCannonProjectile,updateCannonProjectile} from './projectile-visuals.js';
import {Scenery} from './scenery.js';
import {offCameraSpawn} from './spawning.js';
import {SmokeGrenades} from './smoke-grenades.js';
import {WreckFires} from './wreck-fires.js';
import * as THREE from 'three';
import RAPIER from '@dimforge/rapier3d-compat';
import {MAP_SIZE,JEEP_COUNT,MATCH_DURATION,TANKS,AMMO,JEEP,JEEP_AMMO,FIXED_DT,GRAVITY,clamp,approachAngle,angleDelta,ballisticElevation,terrainHeight,seededRandom} from './config.js';
import {createTank,createJeep,makeMaterials} from './models.js';
import {buildTerrain} from './terrain.js';
import {Effects} from './effects.js';
import {resolveDirectionalAim} from './aiming.js';
import {createDebris,disposeDebris} from './debris.js';
import {Ragdolls} from './ragdolls.js';
import {buildShowroom} from './showroom.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {deflectSmallArmsRound} from './ricochet.js';
import {Infantry} from './infantry.js';
import {Visibility} from './visibility.js';
import {EnemyDirector,createPatrol} from './ai.js';
import {Presentation} from './postprocessing.js';
import {AudioEngine} from './audio.js';
const V=()=>new THREE.Vector3();
export class Game {
 constructor(canvas){
  this.canvas=canvas;this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.13;
  this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x596675);this.scene.fog=new THREE.FogExp2(0x74707b,.004);this.camera=new THREE.PerspectiveCamera(43,1,.2,360);this.clock=new THREE.Clock();this.acc=0;this.time=0;this.mode='menu';this.keys=new Set();this.mouse=new THREE.Vector2();this.firing=false;this.altFire=false;this.aim=V();this.cursorAim=V();this.autoTarget=null;this.prediction=V();this.zoom=1;this.shake=0;this.shakeSetting=.6;this.audio=new AudioEngine();this.ammo='ap';this.inventory={he:0,sabot:0};this.kills=0;this.damage=0;this.credits=900;this.selected='medium';this.smokeCooldown=0;this.recoverCooldown=0;this.timer=MATCH_DURATION;this.rand=seededRandom(36);this.onEvent=()=>{};
  const hemi=new THREE.HemisphereLight(0xc8d4ed,0x65566a,1.6);this.hemi=hemi;this.scene.add(hemi);this.sun=new THREE.DirectionalLight(0xffab65,2.15);this.sun.position.set(-55,32,26);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);Object.assign(this.sun.shadow.camera,{left:-65,right:65,top:65,bottom:-65,near:1,far:200});this.sun.shadow.bias=-.0004;this.sun.shadow.normalBias=.07;this.scene.add(this.sun,this.sun.target);const skyFill=new THREE.DirectionalLight(0x8fafff,.6);skyFill.position.set(30,45,-40);this.skyFill=skyFill;this.scene.add(skyFill);
  this.showroomLights=new THREE.Group();this.scene.add(this.showroomLights);this.showroomKey=new THREE.DirectionalLight(0xffe6bd,3.2);this.showroomFill=new THREE.DirectionalLight(0xc5d9ff,1.3);this.showroomLights.add(this.showroomKey,this.showroomKey.target,this.showroomFill,this.showroomFill.target);
  this.presentation=new Presentation(this);this.bindInputs();this.resize();try{const settings=JSON.parse(localStorage.getItem('tankz-settings')||'{}');if(settings.quality==='low'){this.renderer.setPixelRatio(1);this.renderer.shadowMap.enabled=false;this.presentation.resize('low');}}catch{}window.addEventListener('resize',()=>this.resize());
 }
 async init(progress=()=>{}){
  progress('Starting physics',.05);await nextPaint();await RAPIER.init();this.audio.prepare?.();progress('Loading music and mission stingers',.07);await this.audio.loadAssets(import.meta.env.BASE_URL,f=>progress('Loading music and mission stingers',.07+.03*f));let loaded=0;const loader=new THREE.TextureLoader();const urls={droneComposite:'recon-drone-composite',dustBillow:'tank-dust-billow',frontierStone:'frontier-sandstone',cannonMuzzle:'cannon-muzzle-plume',sceneryWood:'scenery-wood',sand:'desert-albedo',normal:'desert-normal',height:'desert-height',armor:'armor-albedo',vanguardAlbedo:'vanguard-armor-albedo',vanguardNormal:'vanguard-armor-normal',vanguardRoughness:'vanguard-armor-roughness',vanguardSpecular:'vanguard-armor-specular',vanguardBump:'vanguard-armor-bump',vanguardGearAlbedo:'vanguard-gear-albedo',vanguardGearNormal:'vanguard-gear-normal',vanguardGearRoughness:'vanguard-gear-roughness',vanguardGearSpecular:'vanguard-gear-specular',vanguardGearBump:'vanguard-gear-bump',vanguardCanvas:'vanguard-canvas-albedo',vanguardCanvasNormal:'vanguard-canvas-normal',vanguardCanvasBump:'vanguard-canvas-bump',vanguardDecal:'vanguard-decal',vanguardLens:'vanguard-lens',vanguardGrime:'vanguard-grime-mask',armorNormal:'armor-normal',armorRoughness:'armor-roughness',kestrelAlbedo:'kestrel-armor-albedo',kestrelNormal:'kestrel-armor-normal',kestrelRoughness:'kestrel-armor-roughness',kestrelSpecular:'kestrel-armor-specular',kestrelBump:'kestrel-armor-bump',marauderAlbedo:'marauder-armor-albedo',marauderNormal:'marauder-armor-normal',marauderRoughness:'marauder-armor-roughness',marauderSpecular:'marauder-armor-specular',marauderBump:'marauder-armor-bump',marauderHazard:'marauder-hazard-albedo',concrete:'concrete-albedo',rock:'rock-albedo',smoke:'smoke',fire:'fire',sparks:'sparks',crater:'crater',showroomSky:'showroom-dusk-sky',fireAtlas:'fire-simulation-atlas'};this.textures={};await Promise.all(Object.entries(urls).map(async([key,file])=>{const t=await loader.loadAsync(`${import.meta.env.BASE_URL}assets/${file}.png`);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.anisotropy=Math.min(8,this.renderer.capabilities.getMaxAnisotropy());if(['droneComposite','dustBillow','frontierStone','cannonMuzzle','sand','armor','vanguardAlbedo','vanguardGearAlbedo','vanguardCanvas','vanguardDecal','vanguardLens','kestrelAlbedo','kestrelSpecular','marauderAlbedo','marauderSpecular','marauderHazard','concrete','rock','fire','sparks','crater','showroomSky','fireAtlas'].includes(key))t.colorSpace=THREE.SRGBColorSpace;if(['dustBillow','cannonMuzzle','vanguardDecal','vanguardLens'].includes(key))t.wrapS=t.wrapT=THREE.ClampToEdgeWrapping;if(key==='fireAtlas'){t.generateMipmaps=false;t.minFilter=THREE.LinearFilter;t.wrapS=t.wrapT=THREE.ClampToEdgeWrapping;}if(key==='normal')t.repeat.set(MAP_SIZE*.055,MAP_SIZE*.055);this.textures[key]=t;progress('Loading vehicle and terrain materials',.1+.43*(++loaded/Object.keys(urls).length));}));
  progress('Uploading materials',.55);await nextPaint();let uploaded=0;for(const t of Object.values(this.textures)){this.renderer.initTexture(t);if(++uploaded%4===0){progress('Uploading materials',.55+.1*uploaded/Object.keys(urls).length);await nextPaint();}}
  this.materials=makeMaterials(this.textures);const pmrem=new THREE.PMREMGenerator(this.renderer),room=new RoomEnvironment();this.showroomEnvironment=pmrem.fromScene(room,.04);room.dispose();pmrem.dispose();progress('Preparing garage, vehicles and effects',.68);await nextPaint();this.buildWorld();
  progress('Preparing lighting and shaders',.78);await nextPaint();this.updateCamera(0);await this.renderer.compileAsync(this.scene,this.camera);const selected=this.selected;let warmed=0;for(const type of Object.keys(TANKS)){this.selectTank(type);await warmScene(this);progress('Preparing '+TANKS[type].name,.8+.17*(++warmed/3));}this.selectTank(selected);await warmScene(this);this.clock.getDelta();this.running=true;this.frame();
 }
 buildWorld(detail=['menu','garage'].includes(this.mode)?'high':'low'){
  this.modelDetail=detail;this.garageModels??=new Map();this.garageTanks=null;this.cameraRig=null;this.awareness=new PlayerAwareness();
  this.showroomTransition=null;this.showroomView=this.mode==='garage'?1:0;
  if(this.world){const retained=detachGarageCache(this);this.drone?.dispose();this.environment?.ruts?.dispose();this.showroom?.userData.dispose?.();this.visibility?.dispose();this.world.free();this.scene.remove(this.root);this.events.free();const geos=new Set(),mats=new Set();this.root.traverse(o=>{if(o.geometry)geos.add(o.geometry);if(o.material)mats.add(o.material);});geos.forEach(g=>{if(!retained.geometries.has(g))g.dispose();});mats.forEach(m=>{if(!retained.materials.has(m))m.dispose();});}
  this.root=new THREE.Group();this.scene.add(this.root);this.world=new RAPIER.World({x:0,y:GRAVITY,z:0});this.world.timestep=FIXED_DT;this.events=new RAPIER.EventQueue(true);this.entities=new Map();this.props=[];this.tanks=[];this.soldiers=[];this.shells=[];this.debris=[];this.smokeClouds=[];this.spawnTimer=0;this.nextId=1;
  this.environment=buildTerrain(this.root,this.world,this.textures,this.materials,this.props,this.entities);this.fx=new Effects(this.root,this.textures.smoke,this.textures);this.fx.surfaceUniforms.terrainSurface.value=this.environment.ruts.surfaceTexture;this.fx.surfaceUniforms.useTerrainSurface.value=1;this.wreckFires=new WreckFires(this);this.smokeGrenades=new SmokeGrenades(this);this.ragdolls=new Ragdolls(this.world,this.root,this.fx);this.player=this.spawnTank(this.selected,0,19,false);this.player.body.setRotation({x:0,y:1,z:0,w:0},true);this.player.body.setTranslation({x:0,y:terrainHeight(0,19)+1.04*this.player.cfg.scale,z:19},true);this.player.yaw=Math.PI;this.player.turretYaw=Math.PI;
  this.autoTarget=null;this.aimBearing=Math.PI;this.aim.set(0,0,-36);this.cursorAim.copy(this.aim);this.world.step();this.syncTank(this.player);this.camera.position.set(10,8,31);this.camera.lookAt(0,1,19);this.acc=0;this.drone=new ReconDrone(this);this.visibility=new Visibility(this);this.fx.visibility=this.visibility;this.director=new EnemyDirector(this);this.stealthKills=0;this.infantryKills=0;this.infantry=new Infantry(this);this.scenery=new Scenery(this);if(detail==='low')this.scenery.deploy();this.showroom=detail==='high'?buildShowroom(this):null;if(detail==='high')prepareGarage(this);
 }
 spawnTank(type,x,z,enemy){
  const jeep=type==='jeep',cfg=jeep?JEEP:TANKS[type],model=jeep?createJeep(this.materials):(this.modelDetail==='high'?this.garageModels?.get(type):null)||createTank(type,this.materials,enemy,this.modelDetail||'low'),body=this.world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(x,terrainHeight(x,z)+1.65,z).setLinearDamping(.12).setAngularDamping(3).setCcdEnabled(true));
  if(!jeep&&this.modelDetail==='high')this.garageModels?.set(type,model);
  const [hx,hz]=cfg.hull||[1.48,1.8],hullPoints=[];for(const x of [-hx,hx])for(const [z,y] of [[-hz,-.02],[.62-hz,-.43],[hz-.62,-.43],[hz,-.02],[hz,.43],[-hz,.43]])hullPoints.push(x*cfg.scale,y*cfg.scale,z*cfg.scale);
  const collider=this.world.createCollider((jeep?RAPIER.ColliderDesc.cuboid(1.04,.48,1.66).setTranslation(0,.13,0):RAPIER.ColliderDesc.convexHull(new Float32Array(hullPoints))).setMass(cfg.mass).setCollisionGroups(0x0002ffff).setSolverGroups(0x0002ffff).setFriction(.28).setRestitution(.05),body);
  model.root.position.copy(body.translation());this.root.add(model.root);const t={id:`tank-${this.nextId++}`,type,cfg,...model,body,collider,hp:cfg.hp,enemy,jeep,spawnTime:this.time||0,shots:0,dustTimer:0,yaw:0,turretYaw:0,localYaw:0,elevation:0,reload:0,secondary:0,trackDistance:0,grounded:0,dead:false,speed:0,turboCharge:1,turboDelay:0,turboLocked:false,boosting:false,aiPhase:this.rand()*6.28,smoke:0,stuck:0,lastPos:V(),aimTarget:V()};if(enemy)t.ai=createPatrol(t);this.tanks.push(t);this.entities.set(collider.handle,t);return t;
 }
 selectTank(type){if(!TANKS[type]||!['menu','garage'].includes(this.mode))return;selectGarageTank(this,type);}
 deploy(){this.audio.start();this.buildWorld('low');this.kills=0;this.damage=0;this.timer=MATCH_DURATION;this.smokeCooldown=0;this.recoverCooldown=0;this.spawned=0;this.mode='playing';this.updateCamera(10);for(let i=0;i<JEEP_COUNT;i++)this.spawnEnemy(i);this.infantry.deploy();this.world.step();this.mode='playing';this.visibility.update(0,true);this.firing=false;this.keys.clear();this.onEvent('deploy');}
 spawnEnemy(i){const points=PATROL_SITES;const nav=this.director?.navigation;nav?.refresh();for(let j=0;j<points.length;j++){let p=points[(i+j)%points.length].map((v,k)=>v+(k?-18:22));if(nav){const cell=nav.freeNear(nav.index({x:p[0],z:p[1]}));if(cell<0)continue;const free=nav.point(cell);p=[free.x,free.z];}if(!offCameraSpawn(this,p[0],p[1],6)||this.tanks.some(t=>!t.dead&&Math.hypot(t.body.translation().x-p[0],t.body.translation().z-p[1])<8))continue;this.spawnTank('jeep',p[0],p[1],true);this.spawned++;return true;}this.spawnTimer=1;return false;}
 setAmmo(key){if(!AMMO[key])return;if(key!=='ap'&&!this.inventory[key]){this.onEvent('toast','No rounds loaded. Purchase ammunition in the garage.');return;}this.ammo=key;this.audio.click();}
 buyAmmo(key){const a=AMMO[key];if(!a||!a.price)return;if(this.credits<a.price){this.onEvent('toast','Insufficient credits. Earn credits by eliminating hostile tanks.');return;}this.credits-=a.price;this.inventory[key]+=a.pack;this.audio.click();this.onEvent('purchase');}
 pause(){if(this.mode==='playing'){this.mode='paused';this.firing=false;this.altFire=false;this.keys.clear();this.onEvent('pause');}else if(this.mode==='paused'){if(this.onResumeRequest)this.onResumeRequest();else this.resume();}}
 resume(){if(this.mode!=='paused')return;this.mode='playing';this.acc=0;this.onEvent('resume');}
 transitionShowroom(screen,reduced=false){const from=this.showroomView??(this.mode==='garage'?1:0),to=screen==='garage'?1:0;this.mode=screen;this.showroomTransition=reduced?null:{from,to,elapsed:0};this.showroomView=reduced?to:from;this.firing=this.altFire=false;this.keys.clear();}
 leave(){this.mode='menu';this.firing=false;this.altFire=false;this.keys.clear();this.buildWorld();this.onEvent('menu');}
 recover(){if(this.recoverCooldown>0||this.player.dead)return;const p=this.player.body.translation();this.player.body.setTranslation({x:p.x,y:terrainHeight(p.x,p.z)+2,z:p.z},true);this.player.body.setRotation(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),this.player.yaw),true);this.player.body.setLinvel({x:0,y:0,z:0},true);this.player.body.setAngvel({x:0,y:0,z:0},true);snapshotVehicle(this.player);this.syncTank(this.player);this.recoverCooldown=12;this.onEvent('toast','Vehicle recovered.');}
 smoke(){if(this.mode!=='playing'||this.smokeCooldown>0||this.player.dead)return;this.smokeGrenades.launch(this.player);this.smokeCooldown=18;this.audio.boom(.18);this.onEvent('toast','Smoke grenades launched');}

 bindInputs(){
  window.addEventListener('keydown',e=>{if(this.loading)return;if(e.code==='Escape'){e.preventDefault();if(!e.repeat)this.pause();return;}if(e.target instanceof HTMLInputElement)return;if(['Space','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();if(this.mode!=='playing')return;this.keys.add(e.code);if(!e.repeat){if(e.code==='KeyE')this.drone.launch();if(e.code==='KeyQ')this.smoke();if(e.code==='KeyR')this.recover();if(e.code==='Digit1')this.setAmmo('ap');if(e.code==='Digit2')this.setAmmo('he');if(e.code==='Digit3')this.setAmmo('sabot');}});
  window.addEventListener('keyup',e=>this.keys.delete(e.code));window.addEventListener('blur',()=>{this.keys.clear();this.firing=false;this.altFire=false;if(this.mode==='playing')this.pause();});
  window.addEventListener('pointermove',e=>{this.mouse.set(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2);});
  this.canvas.addEventListener('pointerdown',e=>{if(this.mode!=='playing')return;this.audio.start();if(e.button===0)this.firing=true;if(e.button===2)this.altFire=true;});window.addEventListener('pointerup',e=>{if(e.button===0)this.firing=false;if(e.button===2)this.altFire=false;});this.canvas.addEventListener('contextmenu',e=>e.preventDefault());
  this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.zoom=clamp(this.zoom+e.deltaY*.0005,.7,1.5);},{passive:false});
 }
 resize(){this.renderer.setSize(innerWidth,innerHeight);this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.presentation?.resize();}
 updateAim(){const raycaster=new THREE.Raycaster();raycaster.setFromCamera(this.mouse,this.camera);const height=this.player.body.translation().y;const plane=new THREE.Plane(new THREE.Vector3(0,1,0),-height);if(raycaster.ray.intersectPlane(plane,this.cursorAim)){const solution=resolveDirectionalAim(this,this.cursorAim);this.autoTarget=solution.target;this.aim.copy(solution.point);}}

 muzzle(t){t.root.updateMatrixWorld(true);return {p:t.muzzlePoint.getWorldPosition(V()),dir:t.muzzlePoint.getWorldDirection(V()).normalize()};}
 commandFor(t){
  if(!t.enemy)return {throttle:(this.keys.has('KeyW')?1:0)-(this.keys.has('KeyS')?1:0),steer:(this.keys.has('KeyA')?1:0)-(this.keys.has('KeyD')?1:0),brake:false,boost:this.keys.has('ShiftLeft')||this.keys.has('ShiftRight'),aim:this.aim,fire:this.firing||this.keys.has('Space'),secondary:this.altFire};
  return this.director.command(t);
 }
 drive(t,cmd,dt){
  const b=t.body,cfg=t.cfg,p=new THREE.Vector3().copy(b.translation()),q=new THREE.Quaternion().copy(b.rotation()),vel=new THREE.Vector3().copy(b.linvel()),ang=new THREE.Vector3().copy(b.angvel());
  const forward=new THREE.Vector3(0,0,1).applyQuaternion(q),right=new THREE.Vector3(1,0,0).applyQuaternion(q),up=new THREE.Vector3(0,1,0).applyQuaternion(q);t.yaw=Math.atan2(forward.x,forward.z);t.speed=vel.dot(forward);t.grounded=0;b.resetForces(true);b.resetTorques(true);
  for(const x of [-(cfg.wheelX||1.12),cfg.wheelX||1.12])for(const z of (t.jeep?[-cfg.wheelZ,cfg.wheelZ]:[-1.68,0,1.68])){const rel=new THREE.Vector3(x*cfg.scale,0,z*cfg.scale).applyQuaternion(q),origin=p.clone().add(rel),down=up.clone().negate();const hit=this.world.castRay(new RAPIER.Ray(origin,down),(cfg.suspensionReach||1.4)*cfg.scale,true,undefined,undefined,undefined,b,c=>{const entity=this.entities.get(c.handle);return !entity?.projectile&&(!entity?.cfg||(entity.jeep&&entity.dead));});if(hit){const compression=(cfg.suspensionRest||1.2)*cfg.scale-hit.timeOfImpact;if(compression>0){const pointVel=vel.clone().add(new THREE.Vector3().crossVectors(ang,rel));const force=clamp(compression*cfg.mass*(cfg.spring||15)-pointVel.dot(up)*cfg.mass*1.55,0,cfg.mass*18);b.addForceAtPoint(up.clone().multiplyScalar(force),origin,true);t.grounded++;}}}
  const boosting=!t.enemy&&updateTurbo(t,cmd,dt);
  if(t.grounded>0){const grip=Math.min(1,t.grounded/4);const engine=cmd.throttle*cfg.power*(boosting?TURBO.power:1)*Math.max(.05,1-Math.max(0,t.speed*Math.sign(cmd.throttle))/(cfg.speed*(boosting?TURBO.speed:1)));b.addForce(forward.clone().multiplyScalar(engine*grip),true);b.addForce(right.clone().multiplyScalar(-vel.dot(right)*cfg.mass*(cmd.brake?1.4:4.2)*grip),true);b.addForce(forward.clone().multiplyScalar(-t.speed*cfg.mass*(cmd.brake?4:.36)),true);b.addTorque({x:0,y:cmd.steer*cfg.mass*12*grip,z:0},true);}
  // Gentle roll stability preserves pitch over hills and airtime.
  const correction=new THREE.Vector3().crossVectors(up,new THREE.Vector3(0,1,0)).multiplyScalar(cfg.mass*4);if(up.y>.2)b.addTorque(correction,true);
  // Solve in world space, including inherited chassis velocity, then transform
  // into the pitched/rolled hull's frame. This prevents hills moving the reticle away.
  this.syncTank(t);for(const w of t.wheels)w.rotation.x+=t.speed*dt*1.56;
  const a=t.jeep?JEEP_AMMO:AMMO[t.enemy?'ap':this.ammo];
  const muzzle=this.muzzle(t).p;const delta=cmd.aim.clone().sub(muzzle);
  let flight=Math.max(.03,Math.hypot(delta.x,delta.z)/a.speed),relative=delta.clone(),pitch=0;
  for(let i=0;i<5;i++){relative.copy(delta).addScaledVector(vel,-flight);const horizontal=Math.hypot(relative.x,relative.z);pitch=ballisticElevation(horizontal,relative.y,a.speed);flight=horizontal/Math.max(1,a.speed*Math.cos(pitch));}
  // Small semi-implicit integration correction matches the 60 Hz projectile step.
  pitch+=-GRAVITY*FIXED_DT/(2*a.speed);
  const heading=Math.atan2(relative.x,relative.z);
  const worldDir=new THREE.Vector3(Math.sin(heading)*Math.cos(pitch),Math.sin(pitch),Math.cos(heading)*Math.cos(pitch));
  const localDir=worldDir.applyQuaternion(q.clone().invert());
  const desiredLocalYaw=Math.atan2(localDir.x,localDir.z);
  const desiredElev=clamp(Math.atan2(localDir.y,Math.hypot(localDir.x,localDir.z)),-.35,.65);
  if(!t.enemy)t.aimAlignment={target:this.autoTarget?.entity||null,yaw:desiredLocalYaw,elevation:desiredElev,reachable:Math.abs(Math.atan2(localDir.y,Math.hypot(localDir.x,localDir.z))-desiredElev)<.01};
  t.localYaw=approachAngle(t.localYaw,desiredLocalYaw,cfg.traverse*dt);
  t.elevation+=clamp(desiredElev-t.elevation,-cfg.elevation*dt,cfg.elevation*dt);
  t.turret.rotation.y=t.localYaw;t.gun.rotation.x=-t.elevation;
  const actualForward=new THREE.Vector3(Math.sin(t.localYaw),0,Math.cos(t.localYaw)).applyQuaternion(q);t.turretYaw=Math.atan2(actualForward.x,actualForward.z);
  t.reload=Math.max(0,t.reload-dt);t.secondary=Math.max(0,t.secondary-dt);

  if(cmd.fire&&t.reload===0)this.fire(t,false);if(cmd.secondary&&t.secondary===0)this.fire(t,true);
  const traveled=Math.hypot(p.x-t.lastPos.x,p.z-t.lastPos.z);t.stuck=Math.abs(cmd.throttle)>.2&&Math.abs(t.speed)<.5?t.stuck+dt:0;if(t.stuck>4)t.stuck=0;
  t.trackDistance+=Math.min(traveled,2);if(!t.jeep&&t.grounded>1&&t.trackDistance>.28&&Math.abs(t.speed)>.5){this.fx.tread(p,t.yaw,1.24*cfg.scale);this.environment?.ruts?.stamp(p,t.yaw,1.24*cfg.scale,cfg.scale);t.trackDistance=0;}
  updateVehicleDust(this,t,dt,p,vel,forward,right,ang);t.lastPos.copy(p);
  // Exhaust stacks puff harder under throttle.
  if(t.exhausts&&!t.dead&&this.fx.emit&&(!t.enemy||t.visibleToPlayer)){t.exhaustTimer=(t.exhaustTimer||0)-dt;if(t.exhaustTimer<=0){const load=Math.min(1,Math.abs(cmd.throttle||0));t.exhaustTimer=.22-.13*load;t.root.updateMatrixWorld();for(const e of t.exhausts)this.fx.emit(e.getWorldPosition(V()),new THREE.Vector3(0,1.4+load*1.6,0),load>.5?0x252321:0x3b3935,(.25+.2*load)*cfg.scale,2.2,'smoke');}}
 }
 syncTank(t){t.root.position.copy(t.body.translation());t.root.quaternion.copy(t.body.rotation());}
 fire(t,secondary){
  const rocket=t.weapon==='rpg',automatic=!rocket&&(secondary||t.jeep),key=(t.jeep||t.infantry)?'jeep-mg':secondary?'mg':t.enemy?'ap':this.ammo;
  const a=rocket?{speed:48,damage:95,radius:3.5,color:0xffa843}:(t.jeep||t.infantry)?JEEP_AMMO:secondary?{speed:115,damage:12,radius:.15,color:0xffdb85}:AMMO[key];
  if(!automatic&&!t.enemy&&key!=='ap'){if(this.inventory[key]<=0){this.ammo='ap';return;}this.inventory[key]--;this.onEvent('inventory');}
  const {p,dir}=this.muzzle(t);p.addScaledVector(dir,.2);const velocity=dir.clone().multiplyScalar(a.speed).add(new THREE.Vector3().copy(t.body.linvel()));
  const body=this.world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(p.x,p.y,p.z).setLinvel(velocity.x,velocity.y,velocity.z).setCcdEnabled(true).setGravityScale(1));
  const collider=this.world.createCollider(RAPIER.ColliderDesc.ball(automatic?.045:.11).setMass(automatic?.03:4).setSensor(automatic).setRestitution(0).setActiveEvents(RAPIER.ActiveEvents.COLLISION_EVENTS),body);
  const mesh=!rocket&&!automatic?createCannonProjectile(a,key):new THREE.Mesh(rocket?new THREE.CylinderGeometry(.07,.11,.8,8).rotateX(Math.PI/2):automatic?new THREE.BoxGeometry(.05,.05,.75):new THREE.SphereGeometry(.13,6,4),new THREE.MeshBasicMaterial({color:rocket?0x566044:a.color}));mesh.position.copy(p);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),dir);this.root.add(mesh);
  mesh.visible=!t.enemy||t.visibleToPlayer!==false;
  const shell={id:`projectile-${this.nextId++}`,projectile:true,body,collider,mesh,owner:t,ammo:a,damage:a.damage*t.cfg.damage,life:0,rocket,trailDistance:0,secondary:automatic,dead:false,previous:p.clone(),incomingVelocity:velocity.clone(),bounces:0};this.shells.push(shell);this.entities.set(collider.handle,shell);
  if(t.enemy)this.awareness?.attack(this.time);
  t.shots=(t.shots||0)+1;
  const priorSight=this.fx.enemyFire;this.fx.enemyFire=!!t.enemy;try{
  if(rocket){t.secondary=4.8;t.aimTime=0;const engine=new THREE.Mesh(new THREE.ConeGeometry(.12,.7,8).rotateX(-Math.PI/2),new THREE.MeshBasicMaterial({color:0xffb34b,toneMapped:false}));engine.material.color.multiplyScalar(3);engine.position.z=-.65;mesh.add(engine);if(!t.enemy||t.visibleToPlayer!==false){this.fx.muzzleJet?.(p,dir,1.3,t.muzzlePoint);this.fx.flash?.(p,90,.12,6);}this.audio.boom(.3,p.distanceTo(this.player.root.position));}
  else if(automatic){if(t.jeep)t.reload=t.cfg.reload;else t.secondary=.11;if(!t.enemy||t.visibleToPlayer!==false){if(this.fx.machineGun)this.fx.machineGun(p,dir,t.muzzlePoint);else this.fx.muzzle(p,dir);}if(t.shots%3===1){this.audio.boom(.08,t.enemy?p.distanceTo(this.player.root.position):0);}}
  else{t.reload=t.cfg.reload;if(!t.enemy||t.visibleToPlayer!==false)this.fx.cannon(p,dir,t.root.position,t.cfg.scale,t.muzzlePoint);t.body.applyImpulse(dir.clone().multiplyScalar(-t.cfg.mass*.45),true);this.audio.boom(.55,t.enemy?p.distanceTo(this.player.root.position):0);if(!t.enemy)this.shake=Math.max(this.shake,.18);}
  }finally{this.fx.enemyFire=priorSight;}
 }
 predict(){const {p,dir}=this.muzzle(this.player);p.addScaledVector(dir,.2);const velocity=dir.multiplyScalar(AMMO[this.ammo].speed).add(new THREE.Vector3().copy(this.player.body.linvel()));const previous=p.clone();for(let i=0;i<300;i++){velocity.y+=GRAVITY*FIXED_DT;p.addScaledVector(velocity,FIXED_DT);const d=p.clone().sub(previous),len=d.length();const hit=this.world.castRay(new RAPIER.Ray(previous,d.normalize()),len,true,undefined,undefined,undefined,this.player.body,c=>!this.entities.get(c.handle)?.projectile);if(hit){this.prediction.copy(previous).addScaledVector(d,hit.timeOfImpact);return;}previous.copy(p);}this.prediction.copy(p);}
 hurt(target,amount,owner,death=null){if(!target||target.dead||target.destroyed||!Number.isFinite(target.hp))return;if(target===owner)return;if(target===this.player&&owner?.enemy&&amount>0)this.awareness?.attack(this.time);target.hp-=amount;if(owner===this.player&&target.enemy)this.damage+=Math.min(amount,Math.max(0,target.hp+amount));if(target.hp>0)return;if(target.scenery){this.scenery.destroy(target,owner);return;}
  if(target.infantry){this.infantry.kill(target,death?.impulse||new THREE.Vector3(0,3,0),false,!!death?.dismember);return;}
  if(target.cfg){this.visibility?.release?.(target);target.dead=true;target.body.resetForces(true);target.body.resetTorques(true);target.armor.color.setHex(0x292824);const p=new THREE.Vector3().copy(target.body.translation());if(target.jeep){target.root.updateWorldMatrix(true,true);target.crew.forEach((crew,i)=>{const launch=new THREE.Vector3((i===0?-1:1)*(4+this.rand()*3),6+this.rand()*3,(this.rand()-.5)*6).applyQuaternion(target.root.quaternion).add(new THREE.Vector3().copy(target.body.linvel()).multiplyScalar(.4));this.ragdolls.eject(crew,launch);});}this.blast(p,target.jeep?1.25:1.8,'vehicle',target.jeep?'jeep':'standard');if(target.jeep){this.prepareJeepWreck(target);this.wreckFires?.start(target);}target.body.setLinearDamping(2);if(target.enemy){this.kills++;this.credits+=120;if(this.kills>=JEEP_COUNT)this.finish(true);else if(this.spawned<JEEP_COUNT)this.spawnTimer=2.5;const stealth=owner===this.player&&!target.ai?.engaged;if(stealth)this.stealthKills++;this.onEvent('kill',stealth?'STEALTH KILL · NO RADIO ALERT  +120 CR':'HOSTILE DESTROYED  +120 CR');}else this.finish(false);}
  else {target.destroyed=true;const p=new THREE.Vector3().copy(target.body.translation());this.root.remove(target.mesh);target.mesh.visible=false;this.entities.delete(target.collider.handle);this.world.removeRigidBody(target.body);this.spawnDebris(p,6,target.explosive?'metal':'masonry');this.fx.explosion(p,.45);if(target.explosive){this.blast(p,1.3,'metal');for(const obj of [...this.tanks,...this.props]){if(obj.destroyed||obj.dead)continue;const dist=new THREE.Vector3().copy(obj.body.translation()).distanceTo(p);if(dist<7)this.hurt(obj,180*(1-dist/7),owner);}}}
 }
 prepareJeepWreck(target){
  // Crumpled hull with beveled sides lets suspension climb from any approach.
  const points=[];for(const [x,z,y] of [[1.12,1.8,-.48],[.64,1.05,.18]])for(const sx of [-1,1])for(const sz of [-1,1])points.push(x*sx,y,z*sz);
  const shape=RAPIER.ColliderDesc.convexHull(new Float32Array(points));target.collider.setShape(shape.shape);target.collider.setTranslationWrtParent({x:0,y:0,z:0});target.collider.setFriction(.55);target.collider.setRestitution(0);
  target.root.children[0].scale.y=.48;target.turret.rotation.z=.55;target.body.setAngularDamping(5);
 }
 blast(p,size,kind='earth',variant='standard',visible=true){this.infantry?.blast(p,size*5,100*size);if(!visible)return;this.fx.explosion(p,size,variant);this.spawnDebris(p,Math.round(size*9),kind);const distance=p.distanceTo(this.player.root.position);this.shake=Math.max(this.shake,Math.min(1,size/(1+distance*.065)));this.audio.boom(size,distance);}
 spawnDebris(p,count,kind='earth'){for(let i=0;i<count;i++){if(this.debris.length>=90){const old=this.debris.shift();this.world.removeRigidBody(old.body);disposeDebris(old);}const fragment=createDebris(this.materials,kind,i,this.rand);const body=this.world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(p.x+(this.rand()-.5),p.y+.5,p.z+(this.rand()-.5)).setLinvel((this.rand()-.5)*13,3+this.rand()*9,(this.rand()-.5)*13).setAngvel({x:this.rand()*9,y:this.rand()*8,z:this.rand()*9}));this.world.createCollider(RAPIER.ColliderDesc.convexHull(fragment.vertices).setMass(kind==='vehicle'?5:2).setRestitution(kind==='vehicle'?.25:.15).setFriction(.8),body);fragment.mesh.position.copy(body.translation());this.root.add(fragment.mesh);this.debris.push({...fragment,body,life:6+this.rand()*4,age:0});}}

 impact(shell,target,point,normal){if(shell.dead||(target?.collider?.handle===shell.ignoreCollider&&shell.life<shell.ignoreUntil))return;const p=point||new THREE.Vector3().copy(shell.body.translation());const visible=!shell.owner?.enemy||!this.visibility||this.visibility.pointVisible(p),priorSight=this.fx.enemyFire;this.fx.enemyFire=!!shell.owner?.enemy;try{if(deflectSmallArmsRound(this,shell,target,p,normal,visible))return;shell.dead=true;let death=null;if(target?.infantry&&!target.dead){const direction=new THREE.Vector3().copy(shell.incomingVelocity||shell.body.linvel()).normalize();if(shell.secondary)target.bulletHits=(target.bulletHits||0)+1;const dismember=!shell.secondary||target.bulletHits>=3;if(visible)this.fx.blood?.(p,direction,shell.secondary?.5:2);death={dismember,impulse:direction.multiplyScalar(shell.secondary?3:9).add(new THREE.Vector3(0,shell.secondary?2:5,0))};}this.hurt(target,shell.damage,shell.owner,death);if(shell.secondary){if(visible)this.fx.muzzle(p,new THREE.Vector3(0,1,0));return;}this.blast(p,shell.ammo.radius>3?1.25:.55,target?.cfg?'metal':target?.explosive?'metal':target?'masonry':'earth','standard',visible);if(shell.ammo.radius>1)for(const obj of [...this.tanks,...this.props]){if(obj===target||obj===shell.owner||obj.dead||obj.destroyed)continue;const dist=new THREE.Vector3().copy(obj.body.translation()).distanceTo(p);if(dist<shell.ammo.radius)this.hurt(obj,shell.damage*.65*(1-dist/shell.ammo.radius),shell.owner);}}finally{this.fx.enemyFire=priorSight;}}
 finish(victory){if(this.mode!=='playing')return;this.mode='results';this.audio.playResult?.(victory);this.firing=false;this.altFire=false;this.keys.clear();if(victory)this.credits+=300;this.onEvent('results',victory);}
 step(dt){
  for(const t of this.tanks){this.syncTank(t);snapshotVehicle(t);}
  this.time+=dt;this.timer=Math.max(0,this.timer-dt);if(this.timer===0){this.finish(false);return;}this.smokeCooldown=Math.max(0,this.smokeCooldown-dt);this.recoverCooldown=Math.max(0,this.recoverCooldown-dt);for(const c of this.smokeClouds)c.time-=dt;this.smokeClouds=this.smokeClouds.filter(c=>c.time>0);
  this.director.update(dt);
  this.awareness?.update(this,dt);
  for(const t of this.tanks){if(!t.dead)this.drive(t,this.commandFor(t),dt);;}
  this.infantry.update(dt);
  for(const shell of this.shells)if(!shell.dead)shell.incomingVelocity=new THREE.Vector3().copy(shell.body.linvel());
  this.environment?.ruts?.update(dt);this.world.step(this.events);this.scenery?.update(dt);this.smokeGrenades?.update(dt);
  this.events.drainCollisionEvents((h1,h2,started)=>{if(!started)return;const a=this.entities.get(h1),b=this.entities.get(h2);if(a?.projectile&&b!==a.owner)this.impact(a,b);if(b?.projectile&&a!==b.owner)this.impact(b,a);});
  for(let i=this.shells.length-1;i>=0;i--){const s=this.shells[i];s.life+=dt;if(!s.dead){const p=new THREE.Vector3().copy(s.body.translation());const delta=p.clone().sub(s.previous),length=delta.length();if(length>0){const hit=this.world.castRayAndGetNormal(new RAPIER.Ray(s.previous,delta.clone().normalize()),length,true,undefined,undefined,s.collider,s.owner.body,c=>!this.entities.get(c.handle)?.projectile&&!(c.handle===s.ignoreCollider&&s.life<s.ignoreUntil));if(hit)this.impact(s,this.entities.get(hit.collider.handle),s.previous.clone().addScaledVector(delta.normalize(),hit.timeOfImpact),hit.normal);p.copy(s.body.translation());}s.mesh.visible=!s.owner.enemy||this.visibility.pointVisible(p);s.mesh.position.copy(p);const travel=new THREE.Vector3().copy(s.body.linvel());if(travel.lengthSq()>1)s.mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),travel.normalize());if(s.rocket){if(s.mesh.visible){const prior=this.fx.enemyFire;this.fx.enemyFire=!!s.owner.enemy;try{this.fx.rocketTrail?.(s.previous,p,s);}finally{this.fx.enemyFire=prior;}}if(s.mesh.children[0])s.mesh.children[0].scale.setScalar(.85+Math.sin(s.life*95)*.15);}else if(!s.secondary)updateCannonProjectile(s.mesh,new THREE.Vector3().copy(s.body.linvel()).length(),s.life);s.previous.copy(p);}
   if(s.dead||s.life>6){this.entities.delete(s.collider.handle);this.world.removeRigidBody(s.body);this.root.remove(s.mesh);s.mesh.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});this.shells.splice(i,1);}}
  for(const t of this.tanks)this.syncTank(t);
  this.infantry.sync();
  this.drone.update(dt);this.visibility.update(dt);
  this.ragdolls.update(dt,this.player);
  for(const p of this.props)if(p.dynamic&&(!p.destroyed||p.crushed)){p.mesh.position.copy(p.body.translation());p.mesh.quaternion.copy(p.body.rotation());}
  for(let i=this.debris.length-1;i>=0;i--){const d=this.debris[i];d.life-=dt;d.age+=dt;if(d.emissive)d.emissive.emissiveIntensity=1.9*Math.exp(-d.age*1.1);d.mesh.position.copy(d.body.translation());d.mesh.quaternion.copy(d.body.rotation());if(d.life<=0){this.world.removeRigidBody(d.body);disposeDebris(d);this.debris.splice(i,1);}}
  if(this.spawnTimer>0){this.spawnTimer-=dt;if(this.spawnTimer<=0&&this.spawned<JEEP_COUNT)this.spawnEnemy(this.spawned);}
 }
 updateCamera(dt){
  const p=this.player.root.position,showroom=!!this.showroom&&(this.mode==='menu'||this.mode==='garage');this.environment.group.visible=!showroom;if(this.showroom)this.showroom.visible=showroom;this.showroomLights.visible=false;this.scene.environment=showroom?this.showroomEnvironment.texture:null;this.scene.environmentIntensity=showroom?.35:1;this.hemi.intensity=showroom?.38:1.6;this.sun.intensity=showroom?.15:2.15;this.skyFill.intensity=showroom?.12:.6;this.scene.background.setHex(showroom?0x171d20:0x596675);this.scene.fog.color.setHex(showroom?0x3c4140:0x74707b);this.scene.fog.density=showroom?.018:.004;this.renderer.toneMappingExposure=showroom?1.05:1.13;const fov=showroom?36:43;if(this.camera.fov!==fov){this.camera.fov=fov;this.camera.updateProjectionMatrix();}this.showroomKey.position.set(p.x+5,p.y+8,p.z-7);this.showroomKey.target.position.copy(p);this.showroomFill.position.set(p.x-5,p.y+4,p.z-2);this.showroomFill.target.position.copy(p);if(this.mode==='playing'||this.mode==='paused'||this.mode==='results'){
   const lead=this.aim.clone().sub(p);lead.y=0;lead.clampLength(0,9);const target=p.clone().addScaledVector(lead,.3);followCamera(this,target,dt);
   if(this.mode==='playing'&&this.shake>0){this.camera.position.x+=(this.rand()-.5)*this.shake*this.shakeSetting;this.camera.position.y+=(this.rand()-.5)*this.shake*this.shakeSetting;}
   this.sun.position.set(p.x-55,32,p.z+26);this.sun.target.position.copy(p);
  }else{if(this.showroomTransition){const t=this.showroomTransition;t.elapsed+=dt;const progress=Math.min(1,t.elapsed/.72),ease=progress*progress*progress*(progress*(progress*6-15)+10);this.showroomView=t.from+(t.to-t.from)*ease;if(progress===1)this.showroomTransition=null;}else this.showroomView=this.mode==='garage'?1:0;const a=2.38,offset=1.7*(1-this.showroomView);this.camera.position.set(p.x+Math.sin(a)*12.4,p.y+3.4,p.z+Math.cos(a)*12.4);this.camera.lookAt(p.x-Math.cos(a)*offset,p.y+.25-.75*this.showroomView,p.z+Math.sin(a)*offset);}
 }
 frame(){if(!this.running)return;if(this.loading){this.clock.getDelta();requestAnimationFrame(()=>this.frame());return;}const frameDelta=this.clock.getDelta(),dt=Math.min(frameDelta,.08);if(this.mode==='playing'){for(const t of this.tanks)this.syncTank(t);this.updateAim();this.acc+=dt;let steps=0;while(this.acc>=FIXED_DT&&steps++<5){if(this.mode!=='playing')break;this.step(FIXED_DT);this.acc-=FIXED_DT;}this.predict();this.fx.damageSmoke(this.player,dt);this.fx.updateRocketLights(this.shells);this.wreckFires.update(dt);this.fx.update(dt,false);}else if(this.mode==='menu'||this.mode==='garage'){this.time+=dt;this.acc=0;this.showroom?.userData.update?.(dt);this.fx.update(dt,false);}else if(this.mode==='results'){this.wreckFires.update(dt);this.fx.update(dt,false);}
  if(['playing','paused','results'].includes(this.mode))for(const t of this.tanks)presentVehicle(t,clamp(this.acc/FIXED_DT,0,1));
  this.drone?.present(clamp(this.acc/FIXED_DT,0,1),this.mode==='playing'?dt:0);
  this.shake*=Math.exp(-dt*9);this.updateCamera(dt);this.fx.updateHeading(this.player,['playing','paused'].includes(this.mode));this.fx.prepare(this.camera);this.audio.setScene?.(this.mode);this.audio.drive(this.player.speed,this.mode==='playing');this.presentation.render(dt);this.onFrame?.(dt,frameDelta);requestAnimationFrame(()=>this.frame());
 }
 project(p){const v=p.clone().project(this.camera);return {x:(v.x*.5+.5)*innerWidth,y:(-.5*v.y+.5)*innerHeight,visible:v.z<1&&v.z>-1&&Math.abs(v.x)<1.1&&Math.abs(v.y)<1.1};}
}
