import {RUIN_SITES,inJumpLane} from './world-layout.js';
import * as THREE from 'three';
import RAPIER from '@dimforge/rapier3d-compat';
import {box,cylinder} from './models.js';
import {terrainHeight} from './config.js';
import {disposeDebris} from './debris.js';
const TYPES={car:{size:[2.1,1.4,4.2],hp:110,mass:650},crate:{size:[1.5,1.35,1.5],hp:45,mass:65},barricade:{size:[3.8,1.25,.7],hp:65,mass:100},fuel:{size:[2,1.9,3.3],hp:130,mass:450},generator:{size:[1.9,1.5,2.4],hp:110,mass:280}};
export class Scenery {
 constructor(game){this.game=game;this.items=[];this.wood=new THREE.MeshStandardMaterial({map:game.textures?.sceneryWood||null,color:0xb8a17c,roughness:.96});}
 spawn(type,x,z,yaw=0){const g=this.game,cfg=TYPES[type],m=g.materials,[w,h,d]=cfg.size;
  // Proxy mesh supplies navigation bounds; visible geometry is built from breakable pieces.
  const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshBasicMaterial({visible:false}));mesh.name=`reactive-${type}`;
  const b=(mat,x,y,z,w,h,d)=>box(mesh,mat,x,y,z,w,h,d),c=(mat,x,y,z,r,h,axis)=>cylinder(mesh,mat,x,y,z,r,h,axis);
  if(type==='crate'){for(const side of [-1,1]){b(this.wood,side*.66,0,0,.12,1.2,1.4);b(this.wood,0,0,side*.66,1.2,1.2,.12);b(this.wood,0,side*.56,0,1.4,.1,1.4);}for(const x of [-.65,.65])for(const z of [-.72,.72])b(this.wood,x,0,z,.14,1.35,.12);for(const z of [-.73,.73])for(const y of [-.48,.48])b(this.wood,0,y,z,1.5,.14,.1);for(const x of [-.45,.45])b(m.steel,x,0,0,.035,1.28,1.45);}
  if(type==='barricade'){for(const x of [-1.35,1.35]){b(this.wood,x,0,0,.18,1.25,.18);b(this.wood,x,-.52,0,.36,.18,.7);}for(const y of [-.2,.28]){b(this.wood,0,y,0,3.8,.28,.13);for(let i=0;i<7;i++){const stripe=b(i%2?m.dark:m.rust,-1.5+i*.5,y,.08,.22,.27,.025);stripe.rotation.z=-.4;}}}
  if(type==='car'){b(m.rust,0,-.25,0,1.85,.38,3.8);b(m.armor,0,.08,1.35,1.9,.3,1.1);b(m.armor,0,.15,-1.45,1.9,.3,.8);b(m.dark,0,.35,-.15,1.5,.55,1.8);b(m.armor,0,.67,-.18,1.62,.10,1.95);for(const x of [-.83,.83]){b(m.rust,x,.12,-.2,.13,.45,2);for(const z of [-1, .75])b(m.armor,x,.42,z,.085,.55,.09);}for(const x of [-1,1])for(const z of [-1.22,1.22]){c(m.track,x,-.42,z,.35,.22,'x');c(m.steel,x*1.12,-.42,z,.18,.04,'x');}for(const x of [-.65,.65])b(m.lamp,x,-.02,1.94,.33,.18,.04);for(const z of [-2,2])b(m.steel,0,-.35,z,1.95,.12,.12);}
  if(type==='fuel'){b(m.rust,0,-.55,0,1.7,.18,2.7);c(m.armor,0,.05,0,.76,2.4,'z');for(const z of [-.8,.8]){const hoop=new THREE.Mesh(new THREE.TorusGeometry(.77,.045,5,16),m.steel);hoop.position.z=z;mesh.add(hoop);}c(m.rust,0,.87,0,.21,.14);for(const x of [-.96,.96])c(m.track,x,-.62,-.4,.32,.22,'x');b(m.steel,0,-.55,1.45,.16,.12,.6);b(m.rust,.78,.1,.4,.10,.3,.5);}
  if(type==='generator'){b(m.dark,0,-.54,0,1.9,.16,2.4);b(m.armor,0,0,0,1.65,1.05,2.05);for(const side of [-1,1]){for(let i=0;i<8;i++)b(m.dark,side*.835,.05,-.75+i*.2,.025,.52,.06);for(const z of [-.85,.85])c(m.track,side*.88,-.55,z,.2,.12,'x');}b(m.dark,0,.08,1.04,.9,.55,.035);for(const x of [-.23,.23])c(m.lamp,x,.18,1.08,.10,.025,'z');c(m.rust,.5,.67,-.5,.055,.5);b(m.steel,0,.62,0,.75,.06,.11);}
  mesh.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});mesh.castShadow=false;mesh.position.set(x,0,z);mesh.rotation.y=yaw;mesh.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(mesh);const y=(g.environment?.surfaceHeight||terrainHeight)(x,z)-bounds.min.y+.02;mesh.position.y=y;
  const body=g.world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(x,y,z).setRotation(mesh.quaternion).setLinearDamping(.6).setAngularDamping(1.5));const collider=g.world.createCollider(RAPIER.ColliderDesc.cuboid(w/2,h/2,d/2).setMass(cfg.mass).setFriction(.65),body);
  const prop={id:`scenery-${g.nextId++}`,scenery:true,kind:type,mesh,body,collider,hp:cfg.hp,maxHp:cfg.hp,dynamic:true,destroyed:false,crushed:false};this.items.push(prop);g.props.push(prop);g.entities.set(collider.handle,prop);g.root.add(mesh);return prop;
 }
 deploy(){for(const [x,z] of RUIN_SITES)for(const [i,type] of Object.keys(TYPES).entries()){const px=x+12+(i%3)*6,pz=z+Math.floor(i/3)*7;if(!inJumpLane(px,pz,4))this.spawn(type,px,pz,i*.7);}}

 update(dt){const g=this.game;for(const prop of this.items){if(prop.destroyed)continue;for(const tank of g.tanks){if(tank.dead||tank.jeep||Math.abs(tank.speed)<.6)continue;const p=prop.body.translation(),t=tank.body.translation();if(Math.hypot(p.x-t.x,p.z-t.z)>6)continue;let contact=false;g.world.contactPair(prop.collider,tank.collider,manifold=>{for(let i=0;i<manifold.numContacts();i++)if(manifold.contactDist(i)<.12)contact=true;});if(contact)g.hurt(prop,dt*(220+Math.abs(tank.speed)*100),tank);if(prop.destroyed)break;}}}
 destroy(prop,owner){const g=this.game,p=new THREE.Vector3().copy(prop.body.translation());prop.destroyed=true;prop.mesh.updateWorldMatrix(true,true);
  if(prop.kind==='car'){prop.crushed=true;prop.mesh.scale.y=.28;const pts=[];for(const [w,d,y] of [[1.12,2.15,-.20],[.7,1.4,.20]])for(const x of [-1,1])for(const z of [-1,1])pts.push(x*w,y,z*d);prop.collider.setShape(RAPIER.ColliderDesc.convexHull(new Float32Array(pts)).shape);prop.collider.setFriction(.55);prop.body.wakeUp();g.spawnDebris(p,5,'metal');g.fx.smoke(p,false);}
  else {const pieces=[...prop.mesh.children].filter(o=>o.isMesh);for(const source of pieces.slice(0,18)){while(g.debris.length>=90){const old=g.debris.shift();g.world.removeRigidBody(old.body);disposeDebris(old);}const pos=source.getWorldPosition(new THREE.Vector3()),q=source.getWorldQuaternion(new THREE.Quaternion()),scale=source.getWorldScale(new THREE.Vector3()),geometry=source.geometry.clone();geometry.scale(scale.x,scale.y,scale.z);const mesh=new THREE.Mesh(geometry,source.material);mesh.position.copy(pos);mesh.quaternion.copy(q);mesh.castShadow=true;const body=g.world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(pos.x,pos.y,pos.z).setRotation(q).setLinvel((g.rand()-.5)*6,2+g.rand()*4,(g.rand()-.5)*6).setAngvel({x:g.rand()*6,y:g.rand()*6,z:g.rand()*6}));const shape=RAPIER.ColliderDesc.convexHull(new Float32Array(geometry.attributes.position.array));g.world.createCollider(shape.setMass(3).setFriction(.7),body);g.root.add(mesh);g.debris.push({mesh,body,life:12,age:0});}g.entities.delete(prop.collider.handle);g.world.removeRigidBody(prop.body);prop.mesh.removeFromParent();g.fx.smoke(p,false);}
  if(prop.kind==='fuel'){g.blast(p,1.5,'metal','fuel');for(const target of [...g.tanks,...g.props]){if(target===prop||target.dead||target.destroyed)continue;const d=new THREE.Vector3().copy(target.body.translation()).distanceTo(p);if(d<7)g.hurt(target,160*(1-d/7),owner);}}
  else if(prop.kind==='generator'){g.fx.ricochet(p,new THREE.Vector3(0,1,0),new THREE.Vector3(1,2,0));g.fx.flash(p,140,.16,8);g.audio.boom(.18,p.distanceTo(g.player.root.position));}
  else g.audio.boom(.12,p.distanceTo(g.player.root.position));
  g.director?.navigation&&(g.director.navigation.refreshAt=-Infinity);if(g.infantry)g.infantry.navigation.refreshAt=-Infinity;
 }
}
