import {TANKS,AMMO,clamp,terrainHeight} from './config.js';
export class UI {
 constructor(game,root){this.g=game;this.root=root;this.screen='menu';this.toastTimer=0;this.win=false;this.lastHud=0;this.fpsFrames=0;this.fpsElapsed=0;this.enemyMarkers=new Map();this.settings={volume:.45,shake:.6,quality:'high',showFps:false};try{Object.assign(this.settings,JSON.parse(localStorage.getItem('tankz-settings')||'{}'));const save=JSON.parse(localStorage.getItem('tankz-profile')||'null');if(save&&Number.isFinite(save.credits)){game.credits=clamp(save.credits,0,999999);game.inventory={he:clamp(Number(save.he)||0,0,9999),sabot:clamp(Number(save.sabot)||0,0,9999)};}}catch{}game.audio.setVolume(this.settings.volume);game.shakeSetting=this.settings.shake;
  game.onEvent=(event,data)=>{if(event==='deploy'||event==='resume')this.show('playing');if(event==='pause')this.show('paused');if(event==='menu')this.show('menu');if(event==='results'){this.win=data;this.persist();this.show('results');}if(event==='kill'){this.persist();this.toast(data);}if(event==='toast')this.toast(data);if(event==='inventory')this.persist();if(event==='purchase'){this.persist();this.show('garage');}};
  game.onFrame=(dt,elapsed)=>this.frame(dt,elapsed);root.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)this.action(b.dataset.action,b.dataset.value);});root.addEventListener('input',e=>this.setting(e.target));this.show('menu');game.renderer.setPixelRatio(this.settings.quality==='low'?1:Math.min(devicePixelRatio,1.7));game.renderer.shadowMap.enabled=this.settings.quality!=='low';game.presentation.resize(this.settings.quality);
 }
 persist(){try{localStorage.setItem('tankz-profile',JSON.stringify({credits:this.g.credits,...this.g.inventory}));}catch{}}
 tag(){return '<span class="eyebrow"><i class="diamond"></i> DESERT OPERATIONS / 01</span>';}
 brand(){return '<div class="brand">TANK<span>Z</span><small>DESERT COMBAT</small></div>';}
 button(action,label,cls='',value=''){return `<button class="${cls}" data-action="${action}" data-value="${value}">${label}</button>`;}
 show(screen,withinTransition=false){if(!withinTransition)this.cancelScreenTransition();this.screen=screen;document.body.dataset.screen=screen;let html='';const g=this.g,c=TANKS[g.selected];
  if(screen==='menu'||screen==='settings')html=`<header class="menu-header">${this.tag()}<span class="build-tag">FIELD TEST <b>0.1</b></span></header><main class="main-menu">${this.brand()}<p class="menu-intro">Heavy metal.<br>Loose sand.</p><nav>${this.button('deploy','<span>01</span> DEPLOY <b>↗</b>','primary menu-button')}${this.button('garage','<span>02</span> GARAGE <b>↗</b>','menu-button')}${this.button('settings','<span>03</span> SETTINGS <b>↗</b>','menu-button')}</nav><div class="operation-note"><i></i><div><b>OPERATION: DUSTLINE</b><p>8 jeeps. Roaming infantry. One tank.</p></div></div></main><aside class="vehicle-caption"><span class="eyebrow">${c.role}</span><h2>${c.name}<sup>${c.number}</sup></h2><span>READY FOR DEPLOYMENT</span></aside><footer class="menu-footer"><span>WASD <em>DRIVE</em> &nbsp; MOUSE <em>AIM</em> &nbsp; LMB / SPACE <em>FIRE</em></span><span>LOCAL SKIRMISH <i class="status-dot"></i></span></footer>`;
  if(screen==='garage')html=`<header class="screen-header">${this.button('menu','← BACK','text-button')}<h1>GARAGE <span>/ SELECT YOUR MACHINE</span></h1><div class="credits">◈ <b>${g.credits.toLocaleString()}</b> <small>CR</small></div></header><aside class="tank-list">${Object.entries(TANKS).map(([id,t],i)=>`<button class="tank-card ${g.selected===id?'selected':''}" data-action="tank" data-value="${id}"><span class="eyebrow">0${i+1} / ${t.role}</span><strong>${t.name}</strong><span class="tank-silhouette">${id==='heavy'?'▰━':'▰─'}</span><small>${id===g.selected?'SELECTED':'SELECT TANK'} <b>↗</b></small></button>`).join('')}</aside><aside class="tank-details"><span class="eyebrow">${c.role} / ${c.number}</span><h2>${c.name}</h2><p>${c.desc}</p><div class="stats">${['MOBILITY','ARMOR','TURRET SPEED','FIREPOWER'].map((s,i)=>`<div><label>${s}<b>${c.stats[i]}</b></label><div class="stat-track"><i style="width:${c.stats[i]}%"></i></div></div>`).join('')}</div><div class="mechanical"><span>TRAVERSE <b>${Math.round(c.traverse*180/Math.PI)}°/s</b></span><span>RELOAD <b>${c.reload.toFixed(2)} s</b></span><span>ARMOR <b>${c.hp}</b></span></div></aside><section class="ammo-shop"><div class="shop-title"><h3>LOAD YOUR ROUNDS</h3><span>Standard AP is always available. Credits are earned in combat.</span></div><div class="shop-cards">${Object.entries(AMMO).map(([id,a])=>`<article><div><b>${a.name}</b><span>${a.label}</span></div><p>${a.desc}</p><footer><span>${id==='ap'?'UNLIMITED':`${g.inventory[id]} LOADED`}</span>${id==='ap'?'<small>STANDARD ISSUE</small>':this.button('buy',`+${a.pack} ROUNDS · ${a.price} CR`,'buy-button',id)}</footer></article>`).join('')}</div></section><footer class="garage-footer"><span>WASD DRIVE · MOUSE AIM · RMB COAXIAL GUN</span>${this.button('deploy','DEPLOY TO DUSTLINE ↗','primary')}</footer>`;
  if(screen==='playing'||screen==='paused')html=this.hud();
  if(screen==='paused'||screen==='settings')html+=`<div class="modal-shade"><section class="settings-panel"><div class="panel-kicker">${screen==='paused'?'SIMULATION PAUSED':'FIELD PREFERENCES'}</div><h1>${screen==='paused'?'TAKE A BREATHER.':'SETTINGS'}</h1><label class="setting-row"><span>MASTER VOLUME</span><input id="volume" type="range" min="0" max="1" step=".05" value="${this.settings.volume}" aria-label="Master volume"><output>${Math.round(this.settings.volume*100)}%</output></label><label class="setting-row"><span>CAMERA SHAKE</span><input id="shake" type="range" min="0" max="1" step=".05" value="${this.settings.shake}" aria-label="Camera shake"><output>${Math.round(this.settings.shake*100)}%</output></label><label class="setting-row"><span>RENDER QUALITY</span><select id="quality"><option value="high" ${this.settings.quality==='high'?'selected':''}>HIGH</option><option value="low" ${this.settings.quality==='low'?'selected':''}>PERFORMANCE</option></select></label><label class="setting-row"><span>FPS COUNTER</span><input id="showFps" type="checkbox" ${this.settings.showFps?'checked':''} aria-label="Show FPS counter"></label><div class="controls-grid"><span><kbd>W A S D</kbd> Drive / steer</span><span><kbd>MOUSE</kbd> Turret direction</span><span><kbd>LMB / SPACE</kbd> Main gun</span><span><kbd>RMB</kbd> Coaxial gun</span><span><kbd>1 2 3</kbd> Ammunition</span><span><kbd>Q</kbd> Smoke screen</span><span><kbd>SHIFT</kbd> Brake / slide</span><span><kbd>R</kbd> Recover tank</span><span><kbd>SCROLL</kbd> Camera zoom</span><span><kbd>ESC</kbd> Pause</span></div><p class="aim-help"><i>◇</i> Point toward a jeep. Range and elevation adjust automatically. <b>⊕</b> Amber crosshair shows the actual shot; let the turret catch up.</p><div class="panel-actions">${this.button(screen==='paused'?'resume':'menu',screen==='paused'?'BACK TO THE FIGHT ↗':'DONE','primary')}${screen==='paused'?this.button('leave','ABANDON MATCH','text-button'):''}</div></section></div>`;
  if(screen==='results')html=`<div class="results-shade"><section class="results-panel"><span class="eyebrow">OPERATION DUSTLINE / AFTER ACTION</span><h1>${this.win?'AREA<br>SECURED.':'TANK<br>DISABLED.'}</h1><p>${this.win?'The dust settles. You are still standing.':g.timer<=0?'Time expired. Regroup and try again.':'The desert takes no prisoners. Refit and return.'}</p><div class="result-stats"><div><b>${g.kills}<small>/ 8</small></b><span>ELIMINATIONS</span></div><div><b>${Math.round(g.damage).toLocaleString()}</b><span>DAMAGE DEALT</span></div><div><b>${g.kills*120+(this.win?300:0)}</b><span>CREDITS EARNED</span></div></div><div class="panel-actions">${this.button('deploy','DEPLOY AGAIN ↗','primary')}${this.button('garage','REFIT IN GARAGE','secondary')}${this.button('menu','MAIN MENU','text-button')}</div></section></div>`;
  html+=`<div id="fps-counter" ${this.settings.showFps?'':'hidden'}>— FPS</div>`;html+='<div id="toast" role="status"></div><div class="mobile-notice">A keyboard and mouse are required to drive this tank.</div>';this.root.innerHTML=html;this.bindHud();if(screen==='settings'||screen==='paused')this.root.querySelector('.settings-panel button')?.focus();if(screen==='settings'){const shade=this.root.querySelector('.modal-shade');for(const child of this.root.children)if(child!==shade)child.inert=true;if(!matchMedia('(prefers-reduced-motion: reduce)').matches){this.screenAnimation=shade.animate([{opacity:0},{opacity:1}],{duration:240,easing:'ease-out'});shade.querySelector('.settings-panel').animate([{transform:'translateY(14px) scale(.985)'},{transform:'translateY(0) scale(1)'}],{duration:300,easing:'cubic-bezier(.2,.7,.2,1)'});}}
 }
 cancelScreenTransition(){this.transitionToken=(this.transitionToken||0)+1;this.screenAnimation?.cancel();this.screenAnimation=null;this.transitioning=false;this.root.inert=false;this.root.removeAttribute('aria-busy');}
 async dismissSettings(){
  const shade=this.root.querySelector('.modal-shade');if(!shade)return;const opacity=getComputedStyle(shade).opacity;this.cancelScreenTransition();const token=this.transitionToken;
  if(!matchMedia('(prefers-reduced-motion: reduce)').matches){this.transitioning=true;this.root.inert=true;this.screenAnimation=shade.animate([{opacity},{opacity:0}],{duration:180,easing:'ease-in',fill:'both'});shade.querySelector('.settings-panel').animate([{transform:getComputedStyle(shade.querySelector('.settings-panel')).transform},{transform:'translateY(10px) scale(.99)'}],{duration:180,easing:'ease-in',fill:'both'});try{await this.screenAnimation.finished;}catch{return;}if(token!==this.transitionToken)return;}
  this.show('menu');this.root.querySelector('[data-action="settings"]')?.focus({preventScroll:true});
 }
 async transitionShowroom(screen){
  this.cancelScreenTransition();const token=this.transitionToken,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  this.g.transitionShowroom(screen,reduced);
  if(reduced){this.show(screen);this.root.querySelector(screen==='garage'?'[data-action="menu"]':'[data-action="garage"]')?.focus({preventScroll:true});return;}
  this.transitioning=true;this.root.inert=true;this.root.setAttribute('aria-busy','true');
  try{
   this.screenAnimation=this.root.animate([{opacity:1},{opacity:0}],{duration:160,easing:'ease-in',fill:'both'});await this.screenAnimation.finished;
   if(token!==this.transitionToken)return;this.show(screen,true);this.screenAnimation.cancel();
   this.screenAnimation=this.root.animate([{opacity:0},{opacity:1}],{duration:420,delay:70,easing:'cubic-bezier(.2,.7,.2,1)',fill:'both'});await this.screenAnimation.finished;
   if(token!==this.transitionToken)return;this.cancelScreenTransition();this.root.querySelector(screen==='garage'?'[data-action="menu"]':'[data-action="garage"]')?.focus({preventScroll:true});
  }catch(error){if(error.name!=='AbortError')throw error;}
 }
 hud(){return `<header class="hud-top"><div class="hud-brand">TANKZ <span>DUSTLINE</span></div><div class="objective"><span>JEEPS ELIMINATED</span><b id="killcount">0 <small>/ 8</small></b><i></i><time id="clock">05:00</time></div>${this.button('pause','Ⅱ','pause-button')}</header><div id="markers"></div><div id="mouse-aim" class="aim-point"><i></i><span>AIM</span></div><div id="impact-aim" class="impact-point"><i></i><b class="impact-dot"></b><span id="range-readout"></span></div><div id="reload-readout"></div><div class="hud-bottom"><section class="vehicle-status"><div class="vehicle-line"><span>${TANKS[this.g.selected].name} / ${TANKS[this.g.selected].number}</span><b id="speed">0 <small>KM/H</small></b></div><div class="armor-line"><span>ARMOR INTEGRITY</span><b id="health"></b></div><div class="health-track"><i id="health-fill"></i></div><div class="status-foot"><span id="drive-status">ENGINE ONLINE</span><span><kbd>R</kbd> RECOVER</span></div></section><section class="weapons">${Object.entries(AMMO).map(([id,a],i)=>`<button data-action="ammo" data-value="${id}" id="ammo-${id}" class="weapon ${this.g.ammo===id?'active':''}"><kbd>${i+1}</kbd><b>${a.name}</b><span id="rounds-${id}">${id==='ap'?'∞':this.g.inventory[id]}</span></button>`).join('')}<button data-action="smoke" class="weapon smoke-weapon"><kbd>Q</kbd><b>SMOKE</b><span id="smoke-time">READY</span></button><div class="weapon-hints">LMB / SPACE FIRE &nbsp; · &nbsp; RMB COAXIAL &nbsp; · &nbsp; SHIFT BRAKE</div></section><section class="map-panel"><header><span>TACTICAL MAP</span><b>N ↑</b></header><canvas id="minimap" width="200" height="170" aria-label="Tactical map showing visible units and buildings"></canvas><footer>DRY REFINERY <span>220 × 220 M</span></footer></section></div>`;}
 bindHud(){this.refs={};for(const id of ['clock','killcount','speed','health','health-fill','drive-status','mouse-aim','impact-aim','range-readout','reload-readout','smoke-time','markers','minimap','toast','fps-counter'])this.refs[id]=this.root.querySelector(`#${id}`);this.mapCtx=this.refs.minimap?.getContext('2d');this.markerEls=[];}
 action(action,value){if(this.transitioning)return;const g=this.g;g.audio.start();g.audio.click();if(action==='deploy')g.deploy();if(action==='garage'){if(this.screen==='menu')this.transitionShowroom('garage');else{g.mode='garage';g.buildWorld();this.show('garage');}}if(action==='menu'){if(this.screen==='garage')this.transitionShowroom('menu');else if(this.screen==='settings')this.dismissSettings();else g.leave();}if(action==='settings'){g.mode='menu';this.show('settings');}if(action==='tank'){g.selectTank(value);this.show('garage');}if(action==='buy')g.buyAmmo(value);if(action==='pause'||action==='resume')g.pause();if(action==='leave')g.leave();if(action==='ammo')g.setAmmo(value);if(action==='smoke')g.smoke();}
 setting(el){const id=el.id;if(!['volume','shake','quality','showFps'].includes(id))return;this.settings[id]=id==='showFps'?el.checked:id==='quality'?el.value:Number(el.value);this.refs['fps-counter'].hidden=!this.settings.showFps;if(el.nextElementSibling?.tagName==='OUTPUT')el.nextElementSibling.textContent=`${Math.round(Number(el.value)*100)}%`;this.g.audio.setVolume(this.settings.volume);this.g.shakeSetting=this.settings.shake;if(id==='quality'){this.g.renderer.setPixelRatio(this.settings.quality==='low'?1:Math.min(devicePixelRatio,1.7));this.g.renderer.shadowMap.enabled=this.settings.quality!=='low';this.g.presentation.resize(this.settings.quality);}try{localStorage.setItem('tankz-settings',JSON.stringify(this.settings));}catch{}}
 toast(text){this.toastTimer=3.5;if(this.refs.toast){this.refs.toast.textContent=text;this.refs.toast.classList.add('visible');}}
 frame(dt,elapsed=dt){this.fpsFrames++;this.fpsElapsed+=elapsed;if(this.fpsElapsed>=.5){if(this.refs['fps-counter'])this.refs['fps-counter'].textContent=`${Math.round(this.fpsFrames/this.fpsElapsed)} FPS`;this.fpsFrames=0;this.fpsElapsed=0;}this.toastTimer-=dt;if(this.toastTimer<=0)this.refs.toast?.classList.remove('visible');if(!['playing','paused'].includes(this.screen))return;const g=this.g,p=g.player,r=this.refs;const health=Math.max(0,p.hp);r.health.textContent=`${Math.ceil(health)} / ${p.cfg.hp}`;r['health-fill'].style.width=`${health/p.cfg.hp*100}%`;r['health-fill'].classList.toggle('low',health/p.cfg.hp<.3);r.speed.innerHTML=`${Math.round(Math.abs(p.speed)*3.6)} <small>KM/H</small>`;r['drive-status'].textContent=p.grounded?'ENGINE ONLINE':'AIRBORNE';r.killcount.innerHTML=`${g.kills} <small>/ 8</small>`;r.clock.textContent=`${Math.floor(g.timer/60).toString().padStart(2,'0')}:${Math.floor(g.timer%60).toString().padStart(2,'0')}`;r['smoke-time'].textContent=g.smokeCooldown>0?`${Math.ceil(g.smokeCooldown)}s`:'READY';
  for(const id of Object.keys(AMMO)){this.root.querySelector(`#ammo-${id}`)?.classList.toggle('active',id===g.ammo);this.root.querySelector(`#rounds-${id}`).textContent=id==='ap'?'∞':g.inventory[id];}
  const desired=g.project(g.cursorAim),impact=g.project(g.prediction);const offscreen=!impact.visible||impact.x<35||impact.x>innerWidth-35||impact.y<100||impact.y>innerHeight-175;impact.x=clamp(impact.x,35,innerWidth-35);impact.y=clamp(impact.y,100,innerHeight-175);impact.visible=true;r['impact-aim'].classList.toggle('offscreen',offscreen);for(const [name,pos] of [['mouse-aim',desired],['impact-aim',impact]]){r[name].style.transform=`translate(${pos.x}px,${pos.y}px)`;r[name].style.display=pos.visible?'':'none';}r['range-readout'].textContent=`${offscreen?'OFFSCREEN · ':g.autoTarget?'AUTO RANGE · ':'IMPACT · '}${Math.round(g.prediction.distanceTo(p.root.position))} M`;r['impact-aim'].classList.toggle('reloading',p.reload>0);r['reload-readout'].textContent=p.reload>0?`RELOADING ${p.reload.toFixed(1)}s`:'GUN READY';r['reload-readout'].style.setProperty('--progress',`${(1-p.reload/p.cfg.reload)*100}%`);
  this.lastHud+=dt;if(this.lastHud>.08){this.lastHud=0;this.drawMap();}this.drawMarkers(dt);
 }
 drawMarkers(dt=1/60){const g=this.g,seen=new Set(),blend=1-Math.exp(-20*dt);for(const t of [...g.tanks,...(g.soldiers||[])]){
  if(!t.enemy||t.dead||!t.visibleToPlayer||t.root.position.distanceTo(g.player.root.position)>85)continue;
  let marker=this.enemyMarkers.get(t);if(!marker||marker.node.parentNode!==this.refs.markers){const node=document.createElement('div');node.className='enemy-marker';node.innerHTML='<span>▼</span>';this.refs.markers.appendChild(node);marker={node,anchor:t.root.position.clone()};this.enemyMarkers.set(t,marker);}
  // Smooth the physics anchor in world space, then project with this frame's camera.
  // Camera motion stays synchronized instead of lagging behind a screen-space tween.
  if(marker.anchor.distanceTo(t.root.position)>10)marker.anchor.copy(t.root.position);else marker.anchor.lerp(t.root.position,blend);
  const pos=g.project(marker.anchor.clone().add({x:0,y:2.5,z:0}));marker.node.style.display=pos.visible?'':'none';marker.node.style.transform=`translate3d(${pos.x}px,${pos.y}px,0) translate(-50%,-100%)`;marker.node.classList.toggle('auto-target',g.autoTarget?.entity===t);seen.add(t);
 }for(const [t,marker] of this.enemyMarkers)if(!seen.has(t)){marker.node.remove();this.enemyMarkers.delete(t);}}

 drawMap(){const c=this.mapCtx;if(!c)return;const g=this.g,w=200,h=170;c.fillStyle='#202822';c.fillRect(0,0,w,h);const sx=x=>(x+110)/220*w,sy=z=>(z+110)/220*h;c.strokeStyle='#3c4435';c.lineWidth=.5;for(let x=0;x<200;x+=25){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();}for(let y=0;y<h;y+=25){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();}c.fillStyle='#66614c';c.strokeStyle='#91856a';c.lineWidth=.8;for(const [x,z] of g.environment.ruins){const left=sx(x-5),top=sy(z-4.5),width=10/220*w,height=9/220*h;c.fillRect(left,top,width,height);c.strokeRect(left,top,width,height);}const vis=g.visibility;for(let z=0;z<vis.size;z++)for(let x=0;x<vis.size;x++){c.fillStyle=`rgba(5,9,17,${(1-vis.data[z*vis.size+x]/255)*.48})`;c.fillRect(x/vis.size*w,z/vis.size*h,w/vis.size+.5,h/vis.size+.5);}for(const t of [...g.tanks,...(g.soldiers||[])]){if(t.dead||(t.enemy&&!t.visibleToPlayer))continue;const p=t.body.translation();c.save();c.translate(sx(p.x),sy(p.z));c.rotate(-t.yaw);c.fillStyle=t.enemy?'#e98661':'#a9ded0';c.beginPath();c.moveTo(0,5);c.lineTo(-3.5,-3);c.lineTo(3.5,-3);c.closePath();c.fill();if(!t.enemy){c.strokeStyle='#a9ded04d';c.beginPath();c.arc(0,0,13,0,Math.PI*2);c.stroke();}c.restore();}}
}
